services:
  - type: web
    name: smart-toilet-dashboard
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false